### ISSUE TITLE
css is uploaded as text/plain

### ISSUE THREAD

**Issue by twistedgrim** [wmadill/weewx-S3upload#5]
im using the latest versions of all and it seems my css is uploaded with the metadata of text/plain instead of text/css.

I fixed it locally on mine. and if I get time Ill throw up a PR, but found that small bug.

Also it would be nice if we could tag off the user as im just using my raspberry pi's 'PI" user not a weewx user.

**Comment by wmadill** [comment]
Thanks for the report. s3cmd has problems setting the css mime-type (see https://github.com/s3tools/s3cmd/issues/643) and since I don't upload css files very often, I just gave up and set it in the S3 bucket by hand. But you are motivating me to try again. This is a late-in-the-evening project so it may take a few days for me to make any progress. Stay tuned!

I'm not sure what you mean "tag off the user". Can you say more? Does something break?

Thanks.

Bill

**Comment by twistedgrim** [comment]
I figured it out btw.. https://s3tools.org/usage  I modified the local version of the S3upload.py

```
cmd.extend(["--guess-mime-type"])
cmd.extend(["--no-mime-magic"])
```

Works great for me now and I verified the S3 bucket CSS files show up properly. Im not sure of any adverse effects for others but it works great for me..


As far as the "tagged off the user"  I envision it as another variable you could add to the report same as  the others and change what user is being used. It looks like its not quite as simple as the command location for the S3 config as I still got some errors. I guess if people understood this is designed for the standard python install and not a apt-get type install, that would help.

**Comment by wmadill** [comment]
That was what I was going to try--thanks for testing it for me! I'll test it some more and check it into the repo. There were some complaints in the issue I mentioned above about whether python-magic is needed or if it should be removed and whether a minified css file causes problems. And whether it was only a problem with subsequent sync's. Suddenly the test matrix got messier!

About the "tagged off the user" idea, do you mean setting some variable in the "S3upload" stanza in weewx.conf? And then that user is what s3cmd runs as? 

I documented using the s3cmd version downloaded from s3tools.org in the README.md. Is that not clear enough or should it be documented elsewhere? I did think about trying to check the version of s3cmd but never followed through. 

Thanks for any suggestions and thanks for testing the

**Comment by twistedgrim** [comment]
> About the "tagged off the user" idea, do you mean setting some variable in the "S3upload" stanza in weewx.conf? And then that user is what s3cmd runs as?

Yeah, setting a variable in the S3Upload stanza for "s3cmduser" or something of that nature. You currently have it hard coded as weewx as that's the user most people use for the python install method.

Another snag I ran into btw has to do with the S3CMD being found by the new search that you have setup. 

Personally I installed weewx via the apt-get ("DEB) method and was using the `pi` user. Everything worked fine when I did a wee_reports but it was bombing out when running the actual timed reports. moving the S3Upload binary to the same location as the other "wee" commands in /usr/bin  obviously as the `understanding paths` part of the wiki below states you could dump the s3cmd in /usr/bin or symlink it. I think whats happening is the environment being run isn't grabbing my users paths but the system paths since im using the "DEB" install.  Your documentation could be updated to point out this as I'm sure its currently written and setup for the "python" install method and works great for that. 

https://github.com/weewx/weewx/wiki/Understanding-paths#installations-using-deb-or-rpm

If I get a chance Ill pop open a PR for these two issues if you are OK with that. Ill most certainly fork it to get it fixed the way I need to show the changes, since I cant push to your repo.

Thanks again for the work Bill..

James

**Comment by wmadill** [comment]
Closed as in previous comment

**Comment by wmadill** [comment]
James, I've really confused github with closing this issue years after you filed it. Anyway, I've reworked the S3upload.py module and cleaned up a bunch of things but also added two optional configuration items to the [[S3upload]] stanza. They let you provide the full path to either or both of the "s3cmd" executable and the ".s3cfg" configuration file. I think that gets to what you were looking for in asking to have some way to set the user in S3upload.py back in 2020. If you still care, try the new version (2.3 now).

Bill

**Comment by wmadill** [comment]
Argh, closing again...

**Comment by wmadill** [comment]
And again
